# Generated by Django 6.0.4 on 2026-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=100)),
                ('stok_sekarang', models.FloatField(default=0)),
                ('satuan', models.CharField(default='gr', max_length=20)),
                ('kategori_zona', models.CharField(choices=[('TOPPING', 'Zona Topping (Boba/Jelly)'), ('TEA', 'Zona Tea Base (Jasmine/Oolong)'), ('DAIRY', 'Zona Dairy & Sugar')], max_length=20)),
            ],
        ),
    ]
