# Generated by Django 6.0.4 on 2026-04-29 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanbaku',
            name='stok_minimal',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='bahanbaku',
            name='kategori_zona',
            field=models.CharField(choices=[('TOPPING', 'Topping'), ('TEA', 'Tea Base'), ('DAIRY', 'Dairy')], max_length=20),
        ),
        migrations.CreateModel(
            name='RiwayatStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_baru', models.FloatField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bahanbaku')),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
            },
        ),
    ]
