# Generated by Django 6.0.4 on 2026-05-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bahanbaku_stok_minimal_alter_bahanbaku_kategori_zona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah_pembeli', models.IntegerField()),
                ('omset', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
