# Generated by Django 6.0.4 on 2026-05-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_datapenjualan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHistorisHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah_antrian', models.IntegerField()),
                ('omset', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deeproast', models.FloatField(default=0)),
                ('four_season', models.FloatField(default=0)),
                ('jasmine', models.FloatField(default=0)),
                ('boba', models.FloatField(default=0)),
                ('paper_cup_besar', models.IntegerField(default=0)),
                ('paper_cup_kecil', models.IntegerField(default=0)),
                ('gula', models.FloatField(default=0)),
                ('gula_cair', models.FloatField(default=0)),
                ('honey_syrup', models.FloatField(default=0)),
                ('konjac_jelly', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
