# Generated by Django 6.0.4 on 2026-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_datahistorisharian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahanbaku',
            name='kategori_zona',
            field=models.CharField(choices=[('TOPPING', 'Topping'), ('TEA', 'Tea Base'), ('DAIRY', 'Dairy'), ('BAHAN_BAKU', 'Bahan Baku')], max_length=20),
        ),
    ]
