# Generated by Django 6.0.4 on 2026-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_bahanbaku_kategori_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahistorisharian',
            name='creamer',
            field=models.FloatField(default=0),
        ),
    ]
