# Generated by Django 6.0.4 on 2026-05-04 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_datahistorisharian_creamer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('penerima', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=50)),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bahanbaku')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
